name               = "planner-app"
compatibility_date = "2025-06-07"
account_id      = "990cd3c99eee0081b454bbcc43d23a9d"
main               = ".svelte-kit/cloudflare/_worker.js"
workers_dev        = true

[observability.logs]
enabled = true

[assets]
directory = ".svelte-kit/cloudflare"
binding   = "ASSETS"

[[d1_databases]]
binding       = "DB"
database_name = "planner-db"
database_id   = "e479a033-6874-4668-b379-afac76207c1d"
